#!/bin/bash
# Add autocomplete support for bd for bash.
_bd()
{
    # Handle spaces in filenames by setting the delimeter to be a newline.
    local IFS=$'\n'
    # Current argument on the command line.
    local cur=${COMP_WORDS[COMP_CWORD]}
    local search=`echo $cur | sed 's|\([^/]*\).*|\1|'`
    local descend=`echo $cur | sed -n 's|[^/]*/\(.*\)|\1|p'`

    # Available directories to autcomplete to.
    local basecomp=`pwd | sed 's|/|\n|g'`
    basecomp=$(compgen -S "/" -W "$basecomp" -- $search)
    # DEBUGLOG echo "cur:$cur base:$basecomp search:$search descend:$descend" >> "$HOME/Projects/bd/bash_completion.d/log.txt"

    if [[ $descend ]] && [[ ! $basecomp =~ " " ]]
    then
        # Find base directory to complete descend path from using bd
        local basedir=`bd $search`
        local completions=$(compgen -d -S "/" -o nospace -- "$basedir$descend")
        # Replace full base dir path with base dir name only, so that bd works
        completions=${completions//$basedir/$basecomp}
        # Escape special characters in paths
        completions=$(echo "$completions" | sed 's|\([ "'\''.,<>]\)|\\\1|g') # '
    else
        local completions=$basecomp
    fi

    COMPREPLY=( $completions )
}
complete -o nospace -F _bd bd
